---
- hosts: localhost
  become: yes

  tasks:
    - name: add named.conf.local PTR-record
      lineinfile: dest=/home/ansible/dnsconf/named.conf.local
                  insertbefore='^#sample_for_add-PTRrecord'
                  line="{{item.line}}"
      with_items:
        - { line: ' ' }
        - { line: 'zone "46.22.172.in-addr.arpa"{' }
        - { line: 'type master; ' }
        - { line: 'file "/etc/bind/db.isilon-ptr";' }
        - { line: '}; ' }
    
    - name: delete space for last word

    - name: add named.conf.local A-record
      lineinfile: dest=/home/ansible/dnsconf/named.conf.local
                  insertbefore='^#sample_for_add-Arecord'
                  line="{{item.line}}"
      with_items:
        - { line: ' ' }
        - { line: 'zone "isilon.com"{' }
        - { line: 'type master;  ' }
        - { line: 'file "/etc/bind/db.isilon";' }
        - { line: '}; ' }
